### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Zumbalamambo** [R4wm/sqlite3_kjv#5]
Where do I get the bible databases from?

**Comment by R4wm** [comment]
this app creates the database from the text file.

you can run it like this:
```bash
$ pwd 
/home/rmintz/go/src/github.com/r4wm/sqlite3_kjv/cmd
$ go run create_sqlite3_kjv.go -dbPath /tmp/kjv.sqlite3.db
```

If you want to just acquire the database, you can get one for x84_64 sqlite3 here: 
https://mintz5.duckdns.org/kjv.db

**Comment by Zumbalamambo** [comment]
@R4wm Thank you!... May I know where can I acquire those text files? I'm looking for text files with multiple translations.

**Comment by R4wm** [comment]
https://raw.githubusercontent.com/R4wm/sqlite3_kjv/master/data/TEXT-PCE-127.txt

or

https://www.bibleprotector.com/

**Comment by Zumbalamambo** [comment]
Thank you
